"""Mock data for demo mode when MySQL is not configured."""
from datetime import datetime, timedelta
import random

CATEGORIES = [
    {"id": "real_estate", "label": "Real Estate",   "icon": "fa-building",      "color": "#00c9a7"},
    {"id": "rentals",     "label": "Rentals",        "icon": "fa-key",           "color": "#ff6b35"},
    {"id": "services",    "label": "Services",       "icon": "fa-tools",         "color": "#3b82f6"},
    {"id": "vehicles",    "label": "Vehicles",       "icon": "fa-car",           "color": "#a855f7"},
    {"id": "electronics", "label": "Electronics",    "icon": "fa-laptop",        "color": "#f59e0b"},
    {"id": "furniture",   "label": "Furniture",      "icon": "fa-couch",         "color": "#ec4899"},
    {"id": "jobs",        "label": "Jobs",           "icon": "fa-briefcase",     "color": "#10b981"},
    {"id": "other",       "label": "Other",          "icon": "fa-th-large",      "color": "#6b7280"},
]

CITIES = ["Miami", "Los Angeles", "New York", "Houston", "Chicago", "Phoenix", "Dallas", "San Antonio"]

NEIGHBORHOODS_BY_CITY = {
    "Miami":       ["Coral Gables", "Brickell", "Wynwood", "Little Havana", "Coconut Grove", "Miami Beach", "Downtown", "Doral", "Hialeah"],
    "Los Angeles": ["DTLA", "Hollywood", "Silver Lake", "Venice", "Koreatown", "Santa Monica", "Echo Park", "West Hollywood", "Culver City"],
    "New York":    ["SoHo", "Brooklyn", "Queens", "Harlem", "Tribeca", "Upper East Side", "Bronx", "Astoria", "Midtown"],
    "Houston":     ["Midtown", "Montrose", "The Heights", "Sugar Land", "Galleria", "Katy", "Medical Center", "Clear Lake"],
    "Chicago":     ["Lincoln Park", "Wicker Park", "River North", "Logan Square", "Pilsen", "Hyde Park", "The Loop"],
    "Phoenix":     ["Scottsdale", "Tempe", "Mesa", "Chandler", "Glendale", "Downtown Phoenix", "Peoria"],
    "Dallas":      ["Frisco", "Plano", "Uptown", "Deep Ellum", "Oak Cliff", "Richardson", "Irving", "Arlington"],
    "San Antonio": ["Tech District", "Alamo Heights", "Stone Oak", "King William", "Pearl District", "Helotes"],
}

CITY_STATS = {
    "Miami":       {"listings": 8_420,  "icon": "fa-umbrella-beach", "trending": True},
    "Los Angeles": {"listings": 12_100, "icon": "fa-film",           "trending": True},
    "New York":    {"listings": 15_300, "icon": "fa-city",           "trending": False},
    "Houston":     {"listings": 6_890,  "icon": "fa-oil-can",        "trending": True},
    "Chicago":     {"listings": 7_240,  "icon": "fa-wind",           "trending": False},
    "Phoenix":     {"listings": 5_130,  "icon": "fa-sun",            "trending": True},
    "Dallas":      {"listings": 6_700,  "icon": "fa-star",           "trending": False},
    "San Antonio": {"listings": 4_200,  "icon": "fa-church",         "trending": False},
}

PLACEHOLDER_IMAGES = {
    "real_estate": "https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=400&q=80",
    "rentals":     "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400&q=80",
    "services":    "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400&q=80",
    "vehicles":    "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=400&q=80",
    "electronics": "https://images.unsplash.com/photo-1550009158-9ebf69173e03?w=400&q=80",
    "furniture":   "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&q=80",
    "jobs":        "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=400&q=80",
    "other":       "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&q=80",
}

MOCK_LISTINGS = [
    {
        "id": 1,
        "title": "Modern 3BR/2BA House – Coral Gables",
        "description": "Spacious renovated home with open floor plan, updated kitchen, and large backyard. Close to top-rated schools and shopping. Perfect for families. Hurricane-impact windows throughout.",
        "category": "real_estate",
        "subcategory": "House for Sale",
        "price": 685000,
        "price_label": "$685,000",
        "city": "Miami",
        "neighborhood": "Coral Gables",
        "image": PLACEHOLDER_IMAGES["real_estate"],
        "is_prime": True,
        "is_verified": True,
        "contact_phone": "+13055550101",
        "contact_whatsapp": "+13055550101",
        "views": 342,
        "created_at": datetime.now() - timedelta(days=2),
        "owner": {"name": "Realty Solutions Inc.", "rating": 4.8, "reviews": 127},
    },
    {
        "id": 2,
        "title": "2BR Apartment for Rent – Downtown",
        "description": "Fully furnished luxury apartment in the heart of downtown. High-speed Wi-Fi, gym, rooftop pool, concierge. Short-term or long-term. Utilities included.",
        "category": "rentals",
        "subcategory": "Apartment Rental",
        "price": 2800,
        "price_label": "$2,800/mo",
        "city": "Los Angeles",
        "neighborhood": "DTLA",
        "image": PLACEHOLDER_IMAGES["rentals"],
        "is_prime": True,
        "is_verified": True,
        "contact_phone": "+13235550202",
        "contact_whatsapp": "+13235550202",
        "views": 218,
        "created_at": datetime.now() - timedelta(days=1),
        "owner": {"name": "Urban Rentals LA", "rating": 4.6, "reviews": 89},
    },
    {
        "id": 3,
        "title": "Licensed Electrician – Residential & Commercial",
        "description": "Fully licensed & insured electrician with 15 years of experience. Panel upgrades, EV charger installation, LED retrofits, new circuits. Same-day service available.",
        "category": "services",
        "subcategory": "Electrician",
        "price": None,
        "price_label": "Free Quote",
        "city": "Houston",
        "neighborhood": "Midtown",
        "image": PLACEHOLDER_IMAGES["services"],
        "is_prime": True,
        "is_verified": True,
        "contact_phone": "+17135550303",
        "contact_whatsapp": "+17135550303",
        "views": 476,
        "created_at": datetime.now() - timedelta(hours=6),
        "owner": {"name": "PowerPro Electric", "rating": 4.9, "reviews": 203},
    },
    {
        "id": 4,
        "title": "2022 Toyota Camry XSE – 28K Miles",
        "description": "One owner, non-smoker, fully loaded XSE trim. Red exterior with black sport interior. Sunroof, JBL audio, wireless CarPlay, blind-spot monitor. Clean Carfax.",
        "category": "vehicles",
        "subcategory": "Sedan",
        "price": 27500,
        "price_label": "$27,500",
        "city": "Dallas",
        "neighborhood": "Frisco",
        "image": PLACEHOLDER_IMAGES["vehicles"],
        "is_prime": False,
        "is_verified": True,
        "contact_phone": "+12145550404",
        "contact_whatsapp": "+12145550404",
        "views": 189,
        "created_at": datetime.now() - timedelta(days=3),
        "owner": {"name": "Marcus T.", "rating": 4.7, "reviews": 12},
    },
    {
        "id": 5,
        "title": "MacBook Pro M3 Max – 14\" Like New",
        "description": "2024 MacBook Pro 14-inch M3 Max, 36GB RAM, 1TB SSD. Space Black. AppleCare+ until 2026. Original box and accessories included. Selling due to upgrade.",
        "category": "electronics",
        "subcategory": "Laptops",
        "price": 2499,
        "price_label": "$2,499",
        "city": "New York",
        "neighborhood": "SoHo",
        "image": PLACEHOLDER_IMAGES["electronics"],
        "is_prime": False,
        "is_verified": False,
        "contact_phone": "+12125550505",
        "contact_whatsapp": "+12125550505",
        "views": 531,
        "created_at": datetime.now() - timedelta(hours=18),
        "owner": {"name": "Alex K.", "rating": 4.3, "reviews": 7},
    },
    {
        "id": 6,
        "title": "Professional Cleaning Services – Move In/Out",
        "description": "Deep cleaning specialists. Move-in/move-out, post-construction, recurring weekly/bi-weekly. Eco-friendly products. Insured team. Satisfaction guaranteed or free re-clean.",
        "category": "services",
        "subcategory": "Cleaning",
        "price": 150,
        "price_label": "From $150",
        "city": "Chicago",
        "neighborhood": "Lincoln Park",
        "image": PLACEHOLDER_IMAGES["services"],
        "is_prime": True,
        "is_verified": True,
        "contact_phone": "+13125550606",
        "contact_whatsapp": "+13125550606",
        "views": 298,
        "created_at": datetime.now() - timedelta(days=1),
        "owner": {"name": "CleanPro Chicago", "rating": 4.8, "reviews": 156},
    },
    {
        "id": 7,
        "title": "Sectional Sofa – West Elm Harmony",
        "description": "West Elm Harmony sectional, dove gray, barely used. 108\" wide L-shape with chaise. Pet-free, smoke-free home. Selling because of relocation. Pickup only.",
        "category": "furniture",
        "subcategory": "Sofas & Sectionals",
        "price": 1200,
        "price_label": "$1,200 OBO",
        "city": "Phoenix",
        "neighborhood": "Scottsdale",
        "image": PLACEHOLDER_IMAGES["furniture"],
        "is_prime": False,
        "is_verified": False,
        "contact_phone": "+16025550707",
        "contact_whatsapp": "+16025550707",
        "views": 94,
        "created_at": datetime.now() - timedelta(days=4),
        "owner": {"name": "Sarah M.", "rating": 5.0, "reviews": 3},
    },
    {
        "id": 8,
        "title": "Senior Software Engineer – Remote / Hybrid",
        "description": "Fintech startup hiring senior full-stack engineer. React, Python, AWS. Competitive salary $140k–$180k + equity. Flexible hours, health/dental/vision, 401k match.",
        "category": "jobs",
        "subcategory": "Technology",
        "price": 160000,
        "price_label": "$140K–$180K/yr",
        "city": "San Antonio",
        "neighborhood": "Tech District",
        "image": PLACEHOLDER_IMAGES["jobs"],
        "is_prime": True,
        "is_verified": True,
        "contact_phone": None,
        "contact_whatsapp": None,
        "views": 724,
        "created_at": datetime.now() - timedelta(hours=3),
        "owner": {"name": "FinovaTech", "rating": 4.5, "reviews": 34},
    },
]

MOCK_LEADS = [
    {
        "id": 1, "listing_id": 3, "listing_title": "Licensed Electrician – Residential & Commercial",
        "requester_name": "James Wilson", "requester_phone": "+17135559001",
        "requester_email": "jwilson@email.com", "city": "Houston",
        "contact_method": "whatsapp", "status": "new",
        "message": "Need panel upgrade for new workshop. 200A service. When can you come by?",
        "created_at": datetime.now() - timedelta(hours=2),
    },
    {
        "id": 2, "listing_id": 6, "listing_title": "Professional Cleaning Services – Move In/Out",
        "requester_name": "Maria Garcia", "requester_phone": "+13125559002",
        "requester_email": "mgarcia@email.com", "city": "Chicago",
        "contact_method": "call", "status": "contacted",
        "message": "Moving out of a 3BR apartment end of month. Need deep clean ASAP.",
        "created_at": datetime.now() - timedelta(hours=8),
    },
    {
        "id": 3, "listing_id": 3, "listing_title": "Licensed Electrician – Residential & Commercial",
        "requester_name": "Robert Chen", "requester_phone": "+17135559003",
        "requester_email": "rchen@email.com", "city": "Houston",
        "contact_method": "email", "status": "qualified",
        "message": "EV charger installation for Tesla Model Y. Have a 200A panel already.",
        "created_at": datetime.now() - timedelta(days=1),
    },
    {
        "id": 4, "listing_id": 8, "listing_title": "Senior Software Engineer – Remote / Hybrid",
        "requester_name": "Priya Sharma", "requester_phone": "+12105559004",
        "requester_email": "psharma@email.com", "city": "Austin",
        "contact_method": "email", "status": "closed_won",
        "message": "8 years experience in fintech, React + FastAPI. Interested in the role.",
        "created_at": datetime.now() - timedelta(days=2),
    },
    {
        "id": 5, "listing_id": 6, "listing_title": "Professional Cleaning Services – Move In/Out",
        "requester_name": "Tom Baker", "requester_phone": "+13125559005",
        "requester_email": "tbaker@email.com", "city": "Chicago",
        "contact_method": "whatsapp", "status": "new",
        "message": "Weekly cleaning for a 2BR condo. Every Saturday morning preferred.",
        "created_at": datetime.now() - timedelta(hours=1),
    },
]

LEAD_STATUS_LABELS = {
    "new":          {"label": "New",          "color": "#3b82f6"},
    "contacted":    {"label": "Contacted",    "color": "#f59e0b"},
    "qualified":    {"label": "Qualified",    "color": "#a855f7"},
    "closed_won":   {"label": "Won",          "color": "#10b981"},
    "closed_lost":  {"label": "Lost",         "color": "#6b7280"},
}

STATS = {
    "total_listings": 48_372,
    "active_users":   91_204,
    "cities_covered": 320,
    "prime_businesses": 1_847,
}
